# Generated by Django 3.0 on 2019-12-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acconts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('authecation', models.BooleanField(default=False)),
                ('file_l', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Acconts')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inform', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('file_l', models.ImageField(null=True, upload_to='')),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Acconts')),
            ],
        ),
    ]
